version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Zipping Lambda function...
      - zip -r sunset.zip index.js package.json
  post_build:
    commands:
      - echo Build complete. Preparing for deployment...
artifacts:
  files:
    - sunset.zip
    - appspec.yml
    - lambda-deploy.sh
